/**
 * Detailed MCP tool descriptions for the GOAT Network DevOps Agent integration.
 *
 * Each entry provides 5–8 sentences covering: purpose, prerequisites,
 * recommended next steps, pitfalls, and related tools.
 *
 * Keys match ACTION_SCHEMAS exactly (snake_case). Cross-references use
 * exact action registry keys.
 */
export const MCP_DESCRIPTIONS: Record<string, string> = {
  full_diagnostic:
    "Runs a complete network diagnostic pipeline in a single call, capturing traffic on the specified ENIs, transforming the pcap data, and producing a comprehensive analysis report with root cause identification. This is the preferred starting point for any network investigation — use it before reaching for individual capture or analysis tools. It requires at least one valid ENI ID (use list_enis to discover available ENIs) and optionally accepts a target host filter and analysis focus (tls, tcp_health, dns, or general). After completion, review the root_cause_indicators and recommended_actions fields in the response for actionable findings. If you need deeper analysis on specific streams after reviewing the report, use diagnose_tcp_stream or other analysis tools with the capture_id from the response. A common pitfall is specifying a very short duration_minutes (under 2) which may not capture enough traffic for meaningful analysis. Related tools for follow-up investigation: diagnose_tcp_stream, check_tls_hello_size, correlate_tcp_streams, detect_retransmissions.",

  list_enis:
    "Lists all available Elastic Network Interfaces (ENIs) in the target VPC, returning their IDs, status, and associated metadata. Use this tool to discover valid ENI IDs before starting any capture — most other tools in this suite require at least one ENI ID as input. You can optionally filter by VPC ID, subnet, or ENI status (available, in-use, associated). After identifying target ENIs, proceed with full_diagnostic for a comprehensive analysis or start_capture for a manual capture pipeline. A common pitfall is targeting ENIs in a different VPC or subnet than the traffic you want to observe. This tool is safe to call at any time without prerequisites. Related tools: full_diagnostic, start_capture.",

  reverse_dns_lookup:
    "Resolves one or more IP addresses to their associated hostnames using reverse DNS lookup, helping identify the services or hosts behind captured traffic. Use this tool when you see unfamiliar IP addresses in capture results and need to map them to known services or endpoints. It accepts up to 20 IP addresses (IPv4 or IPv6) in a single call. After resolving IPs, use the hostnames to inform target_host filters in subsequent capture or analysis calls. A common pitfall is expecting resolution for private IPs that have no PTR records configured — check whether your VPC DNS settings support reverse lookups for the IP range. This tool has no prerequisites and can be called at any time. Related tools: list_enis, full_diagnostic, correlate_tcp_streams.",

  list_captures:
    "Lists all capture sessions with their current status, ENI targets, and timing metadata, providing an overview of active and completed capture activity. This is a read-only status tool that is safe to call at any time without prerequisites — use it to check what captures are available before running analysis tools. You can filter by status (active, completed, failed, or all) and limit the number of results returned. After finding a completed capture, use its capture_id with transform_capture or any analysis tool. A common pitfall is assuming a capture is ready for analysis when its status is still active — always verify the status is completed. Related tools: get_capture_progress, start_capture, transform_capture.",

  get_capture_progress:
    "Returns real-time progress information for a specific capture session, including percentage complete, elapsed time, and packet/byte counts. This is a read-only status tool that is safe to call at any time without prerequisites — use it to monitor an in-progress capture started via start_capture. It requires the capture_id returned from start_capture and reports the current status (initializing, capturing, stopping, completed, or failed). After the status shows completed, proceed with stop_capture if it has not auto-stopped, then transform_capture to prepare data for analysis. A common pitfall is polling too frequently, which adds unnecessary API overhead — check every 10-15 seconds for short captures. Related tools: start_capture, stop_capture, list_captures.",

  cleanup_orphaned_sessions:
    "Identifies and removes orphaned capture sessions that were not properly stopped or cleaned up, freeing associated resources and preventing quota exhaustion. Use this as a maintenance utility when list_captures shows sessions stuck in unexpected states or when you encounter quota errors starting new captures. It accepts a max_age_hours threshold (default 24) and supports dry_run mode to preview cleanup without deleting anything. After cleanup, verify with list_captures that the orphaned sessions are removed before starting new captures. A common pitfall is running cleanup without dry_run first, which may remove sessions that are legitimately long-running. This tool requires authorization and should be used sparingly. Related tools: list_captures, start_capture.",

  start_capture:
    "IMPORTANT: Before calling this tool, you MUST stop and ask the user for explicit confirmation. Present them with: the target ENI IDs, the capture duration, the estimated cost, and ask 'Do you want me to start this capture?' — do NOT proceed without their approval. This tool initiates a new packet capture session on the specified ENIs. It requires at least one valid ENI ID (use list_enis to discover them) and returns a capture_id for tracking. After the user approves and you start the capture, tell them to wait for the capture duration to elapse, then ask if they want you to stop it. The manual pipeline sequence is: list_enis → start_capture (WITH USER APPROVAL) → wait for duration → stop_capture (ASK USER) → transform_capture (ASK USER) → analysis tools. Related tools: stop_capture, get_capture_progress, list_enis.",

  stop_capture:
    "IMPORTANT: Before calling this tool, confirm with the user that they are ready to stop the capture. Ask them: 'The capture has been running for X time. Ready to stop it and proceed to analysis?' This tool terminates an active capture session and finalizes the pcap data. It requires the capture_id returned from start_capture. After stopping, tell the user the capture is complete and ask if they want you to transform the data for analysis. The manual pipeline sequence is: start_capture → stop_capture (ASK USER) → transform_capture (ASK USER) → analysis tools. Related tools: start_capture, transform_capture, get_capture_progress.",

  transform_capture:
    "IMPORTANT: Before calling this tool, confirm with the user: 'Capture is stopped. Shall I transform the data so I can analyze it?' This tool transforms raw pcap data from a completed capture into a structured format that analysis tools can query. It requires the capture_id of a completed capture (status must be completed after stop_capture). After transformation completes, tell the user the data is ready and ask which analysis they want: TLS inspection, TCP health, DNS, or general. The manual pipeline sequence is: start_capture → stop_capture → transform_capture (ASK USER) → analysis tools. Related tools: stop_capture, query_pcap, diagnose_tcp_stream, check_tls_hello_size.",

  query_pcap:
    "Executes a SQL query against the transformed pcap data from a completed capture, enabling flexible ad-hoc analysis of packet-level information. The required parameters are capture_id (string) and sql (string containing the SQL query). Example call: {capture_id: 'abc123', sql: 'SELECT * FROM pcap_logs WHERE dst_port = 443 LIMIT 10'}. Available columns include: frame_time, frame_size, src_ip, dst_ip, src_port, dst_port, protocol, tcp_stream, tcp_seq, tcp_flags, tls_handshake_type, tls_sni, ip_id, ip_fragment_offset. It requires a capture_id from a completed and transformed capture. A common pitfall is using the wrong parameter name — the parameter is called 'sql' and must contain a valid SQL SELECT statement. Related tools: transform_capture, correlate_tcp_streams, diagnose_tcp_stream.",

  search_fragmented_packets:
    "Identifies IP-fragmented packets in the captured traffic, which can indicate MTU issues, path MTU discovery problems, or potential fragmentation-based attacks. Use this when you suspect MTU-related connectivity problems or when full_diagnostic reports fragmentation indicators. It requires a capture_id from a completed and transformed capture — the capture must have gone through stop_capture and transform_capture first. After finding fragmented packets, investigate the source paths with correlate_tcp_streams or check if the fragmentation correlates with TLS issues via check_tls_hello_size. A common pitfall is setting min_fragment_count too high and missing legitimate fragmentation events — start with the default of 2. Related tools: transform_capture, check_tls_hello_size, correlate_tcp_streams, full_diagnostic.",

  correlate_tcp_streams:
    "Groups captured packets into logical TCP streams and reports statistics for each stream including packet counts, byte volumes, duration, and connection state. Use this to understand the overall traffic pattern and identify streams that merit deeper investigation with stream-specific tools. It requires a capture_id from a completed and transformed capture — analysis cannot proceed until stop_capture and transform_capture have been executed. After identifying interesting streams, use diagnose_tcp_stream for detailed health analysis or reconstruct_tcp_handshake to examine connection setup. A common pitfall is not filtering by target_host or port, which can return a large number of streams making it hard to find the relevant ones. Related tools: transform_capture, diagnose_tcp_stream, reconstruct_tcp_handshake, detect_retransmissions.",

  detect_retransmissions:
    "Analyzes captured traffic for TCP retransmissions and calculates retransmission rates per stream, indicating potential packet loss, network congestion, or faulty endpoints. Use this when investigating latency issues or when full_diagnostic flags high retransmission rates in its summary. It requires a capture_id from a completed and transformed capture — the data must be available via transform_capture before this tool can operate. After detecting high retransmission rates, use get_rtt_distribution to check if latency correlates, or classify_tcp_resets to see if connections are being forcibly closed. A common pitfall is using a very low threshold_percent which may flag normal TCP behavior as problematic — the default of 5% is a reasonable starting point. Related tools: transform_capture, get_rtt_distribution, classify_tcp_resets, correlate_tcp_streams.",

  check_tls_hello_size:
    "Inspects TLS ClientHello messages in captured traffic for oversized packets that may cause connection failures due to fragmentation or middlebox incompatibility. Use this when investigating TLS handshake failures, particularly with services behind load balancers or firewalls that have packet size restrictions. It requires a capture_id from a completed and transformed capture — run stop_capture and transform_capture first. After identifying oversized ClientHello messages, check for related fragmentation with search_fragmented_packets or examine the stream health with diagnose_tcp_stream. A common pitfall is setting max_hello_size too low, which will flag normal modern TLS 1.3 handshakes that naturally use larger ClientHello messages — 512 bytes is a reasonable default. Related tools: transform_capture, search_fragmented_packets, diagnose_tcp_stream, full_diagnostic.",

  get_conversation_stats:
    "Computes traffic statistics for the top network conversations (source-destination pairs) in a capture, ranked by packet or byte volume. Use this to identify which endpoints are generating the most traffic and to focus further investigation on high-volume conversations. It requires a capture_id from a completed and transformed capture — analysis cannot run until transform_capture has processed the data. After identifying top conversations, drill into specific streams with correlate_tcp_streams or examine latency with get_request_response_latency. A common pitfall is using a very small top_n value and missing important but lower-volume conversations that may still have issues. Related tools: transform_capture, correlate_tcp_streams, get_request_response_latency, full_diagnostic.",

  reconstruct_tcp_handshake:
    "Reconstructs and analyzes the three-way TCP handshake (SYN, SYN-ACK, ACK) for connections in a capture, reporting timing, completion status, and failure reasons. Use this when investigating connection establishment failures or slow initial connection times between services. It requires a capture_id from a completed and transformed capture — the capture pipeline (stop_capture and transform_capture) must be complete. After finding failed or slow handshakes, investigate further with classify_tcp_resets for abruptly terminated connections or get_rtt_distribution for latency patterns. A common pitfall is not specifying a stream_id or target_host filter, which reconstructs all handshakes and may produce overwhelming output. Related tools: transform_capture, classify_tcp_resets, get_rtt_distribution, correlate_tcp_streams.",

  classify_tcp_resets:
    "Classifies TCP RST (reset) packets by their likely origin (client, server, middlebox, or unknown) and timing, helping identify whether connection terminations are intentional or symptomatic of a problem. Use this when you observe unexpected connection drops or when full_diagnostic reports elevated reset counts. It requires a capture_id from a completed and transformed capture — the data must be prepared via stop_capture and transform_capture first. After classifying resets, use reconstruct_tcp_handshake to see if connections are failing during setup, or detect_retransmissions to check for underlying packet loss. A common pitfall is attributing all resets to network problems when middlebox resets may be legitimate firewall or load balancer behavior. Related tools: transform_capture, reconstruct_tcp_handshake, detect_retransmissions, diagnose_tcp_stream.",

  detect_out_of_order_packets:
    "Identifies TCP packets that arrived at the capture point out of their expected sequence order, which can indicate network path instability, load balancer issues, or asymmetric routing. Use this when you observe application-level timeouts or degraded throughput that may be caused by packet reordering rather than packet loss. It requires a capture_id from a completed and transformed capture — stop_capture and transform_capture must be called first. After detecting reordering, correlate findings with detect_retransmissions (reordering can trigger spurious retransmissions) and get_rtt_distribution for path stability assessment. A common pitfall is using high sensitivity which flags minor reordering that is normal in multi-path network environments — start with medium sensitivity. Related tools: transform_capture, detect_retransmissions, get_rtt_distribution, correlate_tcp_streams.",

  detect_zero_window:
    "Detects TCP zero-window events where a receiver advertises a window size of zero, indicating it cannot accept more data due to buffer exhaustion or application-level backpressure. Use this when investigating throughput problems or when applications report stalled connections without explicit errors. It requires a capture_id from a completed and transformed capture — the capture must be processed through stop_capture and transform_capture before analysis. After detecting zero-window events, examine the affected streams with diagnose_tcp_stream for a full health assessment or check get_rtt_distribution to see if latency spikes correlate. A common pitfall is setting min_duration_ms too high and missing brief but frequent zero-window events that collectively degrade performance. Related tools: transform_capture, diagnose_tcp_stream, get_rtt_distribution, get_conversation_stats.",

  analyze_tcp_options:
    "Examines TCP options negotiated during connection setup (MSS, window scaling, SACK, timestamps, ECN) and flags mismatches between communicating peers that may indicate configuration problems. Use this when investigating throughput issues that may stem from suboptimal TCP configuration rather than network-level problems. It requires a capture_id from a completed and transformed capture — stop_capture and transform_capture are prerequisites. After finding option mismatches, use reconstruct_tcp_handshake to examine the handshake where options were negotiated, or diagnose_tcp_stream for a comprehensive stream health assessment. A common pitfall is assuming all option mismatches are problematic — some asymmetry (like one side not supporting SACK) is common and may not cause issues. Related tools: transform_capture, reconstruct_tcp_handshake, diagnose_tcp_stream, detect_zero_window.",

  get_rtt_distribution:
    "Computes a histogram and statistical summary (min, max, avg, p50, p95, p99) of round-trip times across TCP streams in a capture, revealing latency patterns and outliers. Use this to establish baseline latency profiles or to investigate latency-related complaints from application teams. It requires a capture_id from a completed and transformed capture — the data must be transformed via stop_capture and transform_capture before this tool can analyze it. After reviewing the distribution, investigate high-latency streams with diagnose_tcp_stream or check for retransmission correlation with detect_retransmissions. A common pitfall is capturing too few packets to produce a statistically meaningful distribution — ensure adequate capture duration (at least 2 minutes recommended). Related tools: transform_capture, diagnose_tcp_stream, detect_retransmissions, get_request_response_latency.",

  get_request_response_latency:
    "Measures application-layer request-response latency for HTTP, HTTPS, DNS, or auto-detected protocols, providing per-request timing and aggregate statistics. Use this when investigating application performance complaints that may originate at the protocol layer rather than the network layer. It requires a capture_id from a completed and transformed capture — stop_capture and transform_capture must be run before this tool can operate. After identifying slow requests, correlate with get_rtt_distribution to determine if network latency or application processing time is the bottleneck. A common pitfall is using protocol auto-detection on non-standard ports, which may fail to match request-response pairs — specify the protocol explicitly when the port is non-standard. Related tools: transform_capture, get_rtt_distribution, diagnose_tcp_stream, correlate_tcp_streams.",

  diagnose_tcp_stream:
    "Performs a comprehensive health assessment of one or more TCP streams, combining multiple analysis checks into a single diagnosis with issues, severity levels, health scores, and recommendations. Use this as the primary deep-dive tool after full_diagnostic identifies specific streams of concern, or when you need a focused assessment of a particular connection. It requires a capture_id from a completed and transformed capture — the full capture pipeline (start_capture → stop_capture → transform_capture) must be complete. After reviewing the diagnosis, follow the recommendations field for suggested remediation steps, or use specialized tools like detect_retransmissions or classify_tcp_resets for further evidence. A common pitfall is not specifying a stream_id or target_host, which may analyze all streams and dilute the focus of the diagnosis. Related tools: transform_capture, full_diagnostic, detect_retransmissions, classify_tcp_resets, check_tls_hello_size.",
};
