// Cloudscape "generative AI output label": marks content produced by the model
// (the catalog facts). Placed once per group of AI output, never per row.
import Box from '@cloudscape-design/components/box';
import Icon from '@cloudscape-design/components/icon';

export default function GenAiLabel({ text = 'Generated by AI' }: { text?: string }) {
  return (
    <Box variant="awsui-gen-ai-label">
      <Icon size="small" name="gen-ai" /> {text}
    </Box>
  );
}
