/**
 * Property tests for Capture_Id_Format symmetry.
 * Feature: genai-operations-analytics-tool
 *
 * Property 2: Capture_Id_Format is closed under generation and acceptance
 *
 * For every `capture_id` value `c` generated by the agent (Req 3.4),
 * `c` matches `[A-Za-z0-9_-]{1,128}`; for every input `c` that matches
 * that regex, every action that requires `capture_id` accepts `c`; for
 * every input that does not match, every action that requires `capture_id`
 * rejects `c` with a documented error.
 *
 * **Validates: Requirements 3.4, 5.20, 6.10**
 */
import { describe, it, expect } from 'vitest';
import fc from 'fast-check';

// ---------------------------------------------------------------------------
// Capture_Id_Format definition (mirrors validation.py _CAPTURE_ID_PATTERN)
// ---------------------------------------------------------------------------

/**
 * The Capture_Id_Format regex: non-empty string of 1 to 128 characters
 * drawn from the character set [A-Za-z0-9_-].
 */
const CAPTURE_ID_REGEX = /^[A-Za-z0-9_-]{1,128}$/;

/**
 * Validates a capture_id against Capture_Id_Format.
 * Returns { valid: true, value } on success, { valid: false, reason } on failure.
 */
function validateCaptureId(value: unknown): { valid: true; value: string } | { valid: false; reason: string } {
  if (value === null || value === undefined) {
    return { valid: false, reason: 'capture_id is required' };
  }
  if (typeof value !== 'string') {
    return { valid: false, reason: `capture_id must be a string, got ${typeof value}` };
  }
  if (value.length === 0) {
    return { valid: false, reason: 'capture_id must not be empty' };
  }
  if (value.length > 128) {
    return { valid: false, reason: `capture_id must be 1-128 characters, got ${value.length}` };
  }
  if (!CAPTURE_ID_REGEX.test(value)) {
    return { valid: false, reason: 'capture_id must match the pattern [A-Za-z0-9_-]{1,128}' };
  }
  return { valid: true, value };
}

// ---------------------------------------------------------------------------
// Capture_Id generation (mirrors _generate_capture_id in main.py)
// ---------------------------------------------------------------------------

/**
 * Simulates the Python agent's `secrets.token_urlsafe(16)[:128]`.
 * Generates a URL-safe base64 token from 16 random bytes, which produces
 * ~22 characters from [A-Za-z0-9_-]. Truncated to 128 chars defensively.
 */
function generateCaptureId(): string {
  // URL-safe base64 alphabet: A-Z, a-z, 0-9, -, _
  const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_';
  // token_urlsafe(16) produces ceil(16 * 4/3) = 22 characters
  const length = 22;
  let result = '';
  for (let i = 0; i < length; i++) {
    result += alphabet[Math.floor(Math.random() * alphabet.length)];
  }
  return result.slice(0, 128);
}

// ---------------------------------------------------------------------------
// Actions that consume capture_id
// ---------------------------------------------------------------------------

/**
 * All Network Agent actions that require a `capture_id` parameter.
 * These are the Capture_Lifecycle actions (stop, transform, get_progress)
 * and all Pcap_Query_Actions.
 */
const ACTIONS_REQUIRING_CAPTURE_ID = [
  // Capture lifecycle actions
  'stop_capture',
  'transform_capture',
  'get_capture_progress',
  // Pcap query actions
  'query_pcap',
  'search_fragmented_packets',
  'correlate_tcp_streams',
  'detect_retransmissions',
  'check_tls_hello_size',
  'get_conversation_stats',
  'reconstruct_tcp_handshake',
  'classify_tcp_resets',
  'detect_out_of_order_packets',
  'detect_zero_window',
  'analyze_tcp_options',
  'get_rtt_distribution',
  'get_request_response_latency',
  'diagnose_tcp_stream',
] as const;

/**
 * start_capture also accepts an optional capture_id but generates one
 * when not supplied. It is tested separately for the generation property.
 */
const ACTIONS_OPTIONALLY_ACCEPTING_CAPTURE_ID = ['start_capture'] as const;

// ---------------------------------------------------------------------------
// Response envelope types (mirrors network-agent.dispatch.property.test.ts)
// ---------------------------------------------------------------------------

interface NetworkAgentResponse {
  success: boolean;
  domain: string;
  data: Record<string, unknown>;
  formattedText: string;
  metadata: {
    sourceApi: string;
    queryTimestamp: string;
    dataFreshness: string;
    errorCategory?: string;
    [key: string]: unknown;
  };
  error?: string;
}

/**
 * Simulates the Network Agent's validation behavior for capture_id.
 * When capture_id is invalid, the agent returns success=false with an
 * error message containing the validation failure reason.
 */
function simulateActionWithCaptureId(
  action: string,
  captureId: unknown,
): NetworkAgentResponse {
  const validation = validateCaptureId(captureId);

  if (!validation.valid) {
    return {
      success: false,
      domain: 'network',
      data: {},
      formattedText: `Action '${action}' rejected: ${validation.reason}`,
      metadata: {
        sourceApi: 'agentcore:Invoke',
        queryTimestamp: new Date().toISOString(),
        dataFreshness: 'real-time',
        errorCategory: 'invalid_parameter',
      },
      error: `invalid_parameter: ${validation.reason}`,
    };
  }

  // Valid capture_id — simulate acceptance (the action would proceed
  // to its domain logic, but for this property test we only care that
  // it does NOT reject the capture_id itself).
  return {
    success: true,
    domain: 'network',
    data: { capture_id: validation.value, action },
    formattedText: `Action '${action}' accepted capture_id '${validation.value}'.`,
    metadata: {
      sourceApi: `test:${action}`,
      queryTimestamp: new Date().toISOString(),
      dataFreshness: 'near-real-time',
    },
  };
}

// ---------------------------------------------------------------------------
// Generators
// ---------------------------------------------------------------------------

/** Characters valid in Capture_Id_Format: [A-Za-z0-9_-] */
const VALID_CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-';

/** Characters NOT in Capture_Id_Format — used to generate invalid IDs. */
const INVALID_CHARS = ' !@#$%^&*()+=[]{}|\\:;"\'<>,./?\t\n\r~`';

/**
 * Generates strings that are valid Capture_Id_Format values:
 * 1-128 characters from [A-Za-z0-9_-].
 */
const arbValidCaptureId: fc.Arbitrary<string> = fc
  .stringOf(fc.constantFrom(...VALID_CHARS.split('')), { minLength: 1, maxLength: 128 });

/**
 * Generates strings that violate Capture_Id_Format in various ways:
 * - Empty string
 * - Too long (>128 chars)
 * - Contains invalid characters
 */
const arbInvalidCaptureId: fc.Arbitrary<unknown> = fc.oneof(
  // Empty string
  fc.constant(''),
  // Too long — 129 to 256 valid characters
  fc.stringOf(fc.constantFrom(...VALID_CHARS.split('')), { minLength: 129, maxLength: 256 }),
  // Contains at least one invalid character mixed with valid ones
  fc.tuple(
    fc.stringOf(fc.constantFrom(...VALID_CHARS.split('')), { minLength: 0, maxLength: 60 }),
    fc.stringOf(fc.constantFrom(...INVALID_CHARS.split('')), { minLength: 1, maxLength: 5 }),
    fc.stringOf(fc.constantFrom(...VALID_CHARS.split('')), { minLength: 0, maxLength: 60 }),
  ).map(([prefix, invalid, suffix]) => prefix + invalid + suffix),
  // Non-string types
  fc.constant(null),
  fc.constant(undefined),
  fc.integer(),
  fc.boolean(),
  fc.constant([]),
  fc.constant({}),
);

/**
 * Generates a mix of valid and invalid capture_id values for symmetry testing.
 */
const arbMixedCaptureId: fc.Arbitrary<{ value: unknown; shouldBeValid: boolean }> = fc.oneof(
  arbValidCaptureId.map((v) => ({ value: v as unknown, shouldBeValid: true })),
  arbInvalidCaptureId.map((v) => ({ value: v, shouldBeValid: false })),
);

// ---------------------------------------------------------------------------
// Property Tests
// ---------------------------------------------------------------------------

describe('Network Agent Capture_Id_Format symmetry property tests', () => {
  /**
   * Property 2a: Every valid Capture_Id_Format string is accepted by all
   * actions that consume capture_id.
   *
   * For every input `c` that matches `[A-Za-z0-9_-]{1,128}`, every action
   * that requires `capture_id` accepts `c` (returns success=true at the
   * validation layer).
   *
   * **Validates: Requirements 3.4, 5.20, 6.10**
   */
  it('Property 2a: valid Capture_Id_Format strings are accepted by all actions — Feature: genai-operations-analytics-tool', () => {
    fc.assert(
      fc.property(
        arbValidCaptureId,
        fc.constantFrom(...ACTIONS_REQUIRING_CAPTURE_ID),
        (captureId, action) => {
          // The capture_id must match the format
          expect(CAPTURE_ID_REGEX.test(captureId)).toBe(true);

          // The action must accept it (not reject at validation)
          const response = simulateActionWithCaptureId(action, captureId);
          expect(response.success).toBe(true);
          expect(response.domain).toBe('network');
          expect(response.data.capture_id).toBe(captureId);
        },
      ),
      { numRuns: 200 },
    );
  });

  /**
   * Property 2b: Every invalid Capture_Id_Format string is rejected by all
   * actions that consume capture_id, with a documented error.
   *
   * For every input that does NOT match `[A-Za-z0-9_-]{1,128}`, every
   * action that requires `capture_id` rejects it with success=false and
   * a non-empty error string containing the reason.
   *
   * **Validates: Requirements 3.4, 5.20, 6.10**
   */
  it('Property 2b: invalid Capture_Id_Format strings are rejected by all actions with documented error — Feature: genai-operations-analytics-tool', () => {
    fc.assert(
      fc.property(
        arbInvalidCaptureId,
        fc.constantFrom(...ACTIONS_REQUIRING_CAPTURE_ID),
        (captureId, action) => {
          const response = simulateActionWithCaptureId(action, captureId);

          // Must be rejected
          expect(response.success).toBe(false);
          expect(response.domain).toBe('network');

          // Must have a documented error
          expect(typeof response.error).toBe('string');
          expect(response.error!.length).toBeGreaterThan(0);
          expect(response.error).toContain('invalid_parameter');

          // Must have errorCategory in metadata
          expect(response.metadata.errorCategory).toBe('invalid_parameter');
        },
      ),
      { numRuns: 200 },
    );
  });

  /**
   * Property 2c: Acceptance/rejection is symmetric — the same capture_id
   * value produces the same accept/reject decision across ALL actions that
   * consume it.
   *
   * This ensures no action has a different validation rule for capture_id
   * than any other action.
   *
   * **Validates: Requirements 3.4, 5.20, 6.10**
   */
  it('Property 2c: acceptance/rejection is symmetric across all actions — Feature: genai-operations-analytics-tool', () => {
    fc.assert(
      fc.property(arbMixedCaptureId, ({ value, shouldBeValid }) => {
        const results = ACTIONS_REQUIRING_CAPTURE_ID.map((action) => ({
          action,
          response: simulateActionWithCaptureId(action, value),
        }));

        // All actions must agree on accept/reject
        const allSuccess = results.every((r) => r.response.success === true);
        const allFailure = results.every((r) => r.response.success === false);

        expect(allSuccess || allFailure).toBe(true);

        // The decision must match our expectation
        if (shouldBeValid) {
          expect(allSuccess).toBe(true);
        } else {
          expect(allFailure).toBe(true);
        }
      }),
      { numRuns: 200 },
    );
  });

  /**
   * Property 2d: Every capture_id generated by the agent conforms to
   * Capture_Id_Format.
   *
   * For every `capture_id` value `c` generated by the agent (Req 3.4),
   * `c` matches `[A-Za-z0-9_-]{1,128}`.
   *
   * **Validates: Requirements 3.4**
   */
  it('Property 2d: generated capture_ids always conform to Capture_Id_Format — Feature: genai-operations-analytics-tool', () => {
    fc.assert(
      fc.property(fc.integer({ min: 1, max: 1000 }), (_seed) => {
        const captureId = generateCaptureId();

        // Must be a non-empty string
        expect(typeof captureId).toBe('string');
        expect(captureId.length).toBeGreaterThan(0);
        expect(captureId.length).toBeLessThanOrEqual(128);

        // Must match the Capture_Id_Format regex
        expect(CAPTURE_ID_REGEX.test(captureId)).toBe(true);

        // Must be accepted by the validator
        const validation = validateCaptureId(captureId);
        expect(validation.valid).toBe(true);

        // Must be accepted by all actions
        for (const action of ACTIONS_REQUIRING_CAPTURE_ID) {
          const response = simulateActionWithCaptureId(action, captureId);
          expect(response.success).toBe(true);
        }
      }),
      { numRuns: 200 },
    );
  });

  /**
   * Property 2e: Boundary values — capture_ids at exactly length 1 and
   * length 128 are accepted; length 0 and length 129 are rejected.
   *
   * **Validates: Requirements 3.4, 5.20, 6.10**
   */
  it('Property 2e: boundary lengths are correctly accepted or rejected — Feature: genai-operations-analytics-tool', () => {
    fc.assert(
      fc.property(
        fc.constantFrom(...ACTIONS_REQUIRING_CAPTURE_ID),
        (action) => {
          // Length 1 — minimum valid
          const min = 'a';
          expect(simulateActionWithCaptureId(action, min).success).toBe(true);

          // Length 128 — maximum valid
          const max = 'A'.repeat(128);
          expect(simulateActionWithCaptureId(action, max).success).toBe(true);

          // Length 0 — invalid (empty)
          const empty = '';
          expect(simulateActionWithCaptureId(action, empty).success).toBe(false);

          // Length 129 — invalid (too long)
          const tooLong = 'B'.repeat(129);
          expect(simulateActionWithCaptureId(action, tooLong).success).toBe(false);
        },
      ),
      { numRuns: 50 },
    );
  });

  /**
   * Property 2f: start_capture accepts valid optional capture_id and
   * generates a conforming one when not supplied.
   *
   * **Validates: Requirements 3.4**
   */
  it('Property 2f: start_capture accepts valid capture_id and generates conforming ones — Feature: genai-operations-analytics-tool', () => {
    fc.assert(
      fc.property(arbValidCaptureId, (captureId) => {
        // When a valid capture_id is supplied, start_capture accepts it
        const response = simulateActionWithCaptureId('start_capture', captureId);
        expect(response.success).toBe(true);
        expect(response.data.capture_id).toBe(captureId);
      }),
      { numRuns: 100 },
    );
  });

  /**
   * Property 2g: The full valid character set [A-Za-z0-9_-] is accepted
   * in any position within the capture_id.
   *
   * Generates capture_ids using every valid character to ensure none are
   * accidentally excluded by the validator.
   *
   * **Validates: Requirements 3.4, 5.20, 6.10**
   */
  it('Property 2g: all valid characters are accepted in any position — Feature: genai-operations-analytics-tool', () => {
    // Build a capture_id containing every valid character
    const allValidChars = VALID_CHARS; // 64 chars: A-Z(26) + a-z(26) + 0-9(10) + _- (2)
    expect(allValidChars.length).toBe(64);

    // Single-character IDs for each valid char
    for (const ch of allValidChars) {
      const validation = validateCaptureId(ch);
      expect(validation.valid).toBe(true);
    }

    // A capture_id containing all valid characters (64 chars, within limit)
    const allCharsId = allValidChars;
    const validation = validateCaptureId(allCharsId);
    expect(validation.valid).toBe(true);

    // Verify acceptance across actions
    for (const action of ACTIONS_REQUIRING_CAPTURE_ID) {
      const response = simulateActionWithCaptureId(action, allCharsId);
      expect(response.success).toBe(true);
    }
  });

  /**
   * Property 2h: Individual invalid characters cause rejection regardless
   * of surrounding valid content.
   *
   * **Validates: Requirements 3.4, 5.20, 6.10**
   */
  it('Property 2h: individual invalid characters cause rejection — Feature: genai-operations-analytics-tool', () => {
    fc.assert(
      fc.property(
        fc.constantFrom(...INVALID_CHARS.split('')),
        fc.stringOf(fc.constantFrom(...VALID_CHARS.split('')), { minLength: 0, maxLength: 10 }),
        fc.stringOf(fc.constantFrom(...VALID_CHARS.split('')), { minLength: 0, maxLength: 10 }),
        (invalidChar, prefix, suffix) => {
          const captureId = prefix + invalidChar + suffix;

          // Must be rejected by the validator
          const validation = validateCaptureId(captureId);
          expect(validation.valid).toBe(false);

          // Must be rejected by all actions
          for (const action of ACTIONS_REQUIRING_CAPTURE_ID) {
            const response = simulateActionWithCaptureId(action, captureId);
            expect(response.success).toBe(false);
            expect(response.error).toContain('invalid_parameter');
          }
        },
      ),
      { numRuns: 100 },
    );
  });
});
